// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PX.DAL.Context;

namespace PX.DAL.Migrations
{
    [DbContext(typeof(PxDbContext))]
    internal class PxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PX.DAL.DTO.Company", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("EstablishmentYear");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100);

                b.HasKey("Id");

                b.ToTable("Companies");
            });

            modelBuilder.Entity("PX.DAL.DTO.Employee", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<long>("CompanyId");

                b.Property<DateTime>("DateOfBirth");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100);

                b.Property<int>("JobTitle");

                b.Property<string>("Surname")
                    .IsRequired()
                    .HasMaxLength(100);

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("Employees");
            });

            modelBuilder.Entity("PX.DAL.DTO.Employee", b =>
            {
                b.HasOne("PX.DAL.DTO.Company", "Company")
                    .WithMany("Employees")
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}